language: rust
sudo: true
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
env:
  global:
    - CARGO_MAKE_RUN_CODECOV="true"
script:
  - hash cargo-make || cargo install cargo-make
  - cargo make workspace-ci-flow --no-workspace
