language: rust
sudo: true
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - '[[ "$TRAVIS_RUST_VERSION" == nightly ]] && export CARGO_MAKE_RUN_CODECOV=true'
  - hash cargo-make || cargo install cargo-make
  - cargo make workspace-ci-flow --no-workspace
