language: rust
sudo: true

os:
  - linux
  - windows

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  exclude:
    # Added in include: with GH_TOKEN env var for GitHub pages
    - rust: stable
      os: linux
  include:
    - rust: stable
      os: linux
  fast_finish: true

cache: cargo

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      BUILD_BAT_PATH=$(tr '/' '\\' <<< "$TRAVIS_BUILD_DIR/build.bat" | sed 's#^\\\(.\)\\#\U\1:\\#')
      echo "$BUILD_BAT_PATH"
      cmd.exe /C "$BUILD_BAT_PATH"
    else
      if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then export CARGO_MAKE_RUN_CODECOV=true; fi
      if hash cargo-make || cargo install cargo-make; then
        cargo make workspace-ci-flow --no-workspace
      fi
    fi
