[package]
name = "efivar"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
byteorder = "1.3.1"
bitflags = "1.0.4"
failure = "0.1.5"
serde = "1.0.90"
serde_derive = "1.0.90"
toml = "0.5.0"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.7"
features = ["winbase", "winnt", "processthreadsapi", "securitybaseapi", "handleapi"]
