[package]
name = "efivar"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]

[dependencies]
base64 = "0.9"
byteorder = "1.2"
bitflags = "1.0"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
