[package]
name = "efivar"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
bitflags = "1.0.4"
failure = "0.1.5"

base64 = { version = "0.10.1", optional = true }
serde = { version = "1.0.91", optional = true }
serde_derive = { version = "1.0.91", optional = true }
toml = { version = "0.5.0", optional = true }

[features]
store = ["base64", "serde", "serde_derive", "toml"]

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.7"
features = ["winbase", "winnt", "processthreadsapi", "securitybaseapi", "handleapi"]
