[package]
name = "efiboot"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
description = "EFI boot manager variable editor written in Rust"

[dependencies]
clap = "2.32"
efivar = { path = "../efivar" }
itertools = "0.7"
