[package]
name = "efiboot"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
description = "EFI boot manager variable editor written in Rust"
edition = "2018"

[dependencies]
clap = "2.33.0"
efivar = { path = "../efivar", features = ["store"] }
itertools = "0.8.0"
